name: tdd
version: 1
description: 测试驱动开发工作流 - 测试 → 实现 → 文档
artifacts:
  - id: spec
    generates: spec.md
    description: 定义需求的特性规范
    template: spec.md
    instruction: |
      创建定义“要构建什么”的特性规范。

      章节：
      - **Feature**: 特性名称及其目的和用户价值的高层说明
      - **Requirements**: 具体需求的列表。使用规范性语言。
      - **Acceptance Criteria**: 使用 当/那么（WHEN/THEN）格式的可测试标准

      格式要求：
      - 每个需求都应当具体且可测试
      - 为验收标准使用 `#### Scenario: <名称>` 以及 当/那么 格式
      - 明确定义边缘情况和错误场景
      - 每个需求必须至少有一个场景

      示例：
      ```
      ## Feature: 用户身份验证

      用户可以安全地登录应用程序。

      ## 需求

      ### 需求：密码验证
      系统应当验证密码是否满足最低安全要求。

      #### 场景：接受有效的密码
      - **当** 密码包含 8 个以上字符、大写字母、小写字母和数字
      - **那么** 密码被接受

      #### 场景：拒绝弱密码
      - **当** 密码少于 8 个字符
      - **那么** 系统显示“密码太短”错误
      ```

      此规范驱动测试创建 —— 每个场景都成为一个测试用例。
    requires: []

  - id: tests
    generates: "tests/*.test.ts"
    description: 在实现之前编写的测试文件
    template: test.md
    instruction: |
      在实现之前编写测试（TDD 红色阶段）。

      文件命名：
      - 将测试文件创建为 `tests/<feature>.test.ts`
      - 每个特性/功能对应一个测试文件
      - 使用与规范匹配的描述性名称

      测试结构：
      - 使用与规范场景匹配的 Given/When/Then 格式
      - 使用 `describe()` 块对相关测试进行分组
      - 规范中的每个场景至少对应一个 `it()` 测试

      覆盖率要求：
      - 覆盖规范中的每个需求
      - 包含正常路径（成功案例）
      - 包含边缘情况（边界条件）
      - 包含错误场景（无效输入、失败）
      - 测试最初应当失败（因为尚未实现）

      示例：
      ```typescript
      describe('密码验证', () => {
        it('接受满足所有要求的有效密码', () => {
          // GIVEN 满足所有要求的密码
          const password = 'SecurePass1';
          // WHEN 验证
          const result = validatePassword(password);
          // THEN 它应当被接受
          expect(result.valid).toBe(true);
        });

        it('拒绝少于 8 个字符的密码', () => {
          // GIVEN 一个短密码
          const password = 'Short1';
          // WHEN 验证
          const result = validatePassword(password);
          // THEN 它应当被拒绝并显示消息
          expect(result.valid).toBe(false);
          expect(result.error).toBe('密码太短');
        });
      });
      ```

      严格遵循规范要求 —— 测试是对规范的验证。
    requires:
      - spec

  - id: implementation
    generates: "src/*.ts"
    description: 使测试通过的实现代码
    template: implementation.md
    instruction: |
      实现特性以使测试通过（TDD 绿色阶段）。

      TDD 工作流：
      1. 运行测试 —— 确认它们失败（红色）
      2. 编写最少量的代码以通过一个测试
      3. 运行测试 —— 确认该测试通过（绿色）
      4. 在保持测试通过的同时，根据需要进行重构
      5. 对下一个失败的测试重复上述步骤

      实现指南：
      - 编写最少量的代码以通过每个测试 —— 不多也不少
      - 频繁运行测试以验证进度
      - 保持函数简短且专注
      - 使用清晰、描述性的名称

      代码组织：
      - 在 `src/<feature>.ts` 中创建源文件
      - 清晰地导出公共 API
      - 保持实现细节私有
      - 为公共函数添加 JSDoc 注释

      示例结构：
      ```typescript
      /**
       * 验证密码是否满足安全要求。
       * @param password - 要验证的密码
       * @returns 包含 valid 标志和可选错误的验证结果
       */
      export function validatePassword(password: string): ValidationResult {
        if (password.length < 8) {
          return { valid: false, error: '密码太短' };
        }
        // ... 其他检查
        return { valid: true };
      }
      ```

      不要过度设计 —— 只实现测试要求的内容。
    requires:
      - tests

  - id: docs
    generates: "docs/*.md"
    description: 已实现特性的文档
    template: docs.md
    instruction: |
      记录已实现的特性。

      章节：
      - **概述**: 特性的功能及其存在的原因（1-2 段）
      - **快速开始**: 立即使用该特性的快速入门指南
      - **示例**: 展示常见用例的代码示例
      - **参考**: 详细的 API 文档、配置选项

      指南：
      - 为用户编写，而不是为开发人员编写
      - 从最常见的用例开始
      - 包含可复制粘贴的代码示例
      - 记录所有带默认值的配置选项
      - 注明任何限制、边缘情况或陷阱
      - 链接到相关的特性或规范

      示例结构：
      ```markdown
      ## 概述

      密码验证可确保用户密码在创建帐户或更改密码之前满足安全要求。

      ## 快速开始

      导入并使用验证函数：

      ```typescript
      import { validatePassword } from './password';

      const result = validatePassword('MySecurePass1');
      if (!result.valid) {
        console.error(result.error);
      }
      ```

      ## 示例

      ### 基础验证
      ...

      ### 自定义错误处理
      ...

      ## 参考

      ### validatePassword(password)

      | 参数 | 类型 | 说明 |
      |-----------|------|-------------|
      | password | string | 要验证的密码 |

      **返回**: `{ valid: boolean, error?: string }`
      ```

      参考规范获取需求，参考实现了解细节。
    requires:
      - implementation

apply:
  requires: [tests]
  tracks: null
  instruction: |
    运行测试以查看失败项。编写最少量的代码以通过每个测试。在保持测试通过的同时进行重构。
