name: spec-driven
version: 1
description: 默认 OpenSpec 工作流 - 提案 → 规范 → 设计 → 任务
artifacts:
  - id: proposal
    generates: proposal.md
    description: 概述变更的初始提案文档
    template: proposal.md
    instruction: |
      创建提案文档，阐明为什么需要这项变更。

      章节：
      - **Why**: 用 1-2 句话说明问题或机会。这解决了什么问题？为什么是现在？
      - **What Changes**: 变更的列表。明确说明新功能、修改或移除。使用 **BREAKING** 标记破坏性变更。
      - **Capabilities**: 确定将创建或修改哪些规范：
        - **New Capabilities**: 列出引入的新功能。每个功能都将对应一个新的 `specs/<name>/spec.md`。使用 kebab-case 命名（例如：`user-auth`, `data-export`）。
        - **修改功能**: 列出需求发生变化的现有功能。仅当规范层面的行为发生变化时（不只是实现细节）才包含在内。每个功能都需要一个增量规范文件。检查项目目录中的 `specs/` 以获取现有的规范名称。如果没有需求变化，请保持为空。
      - **Impact**: 受影响的代码、API、依赖或系统。

      重要提示：Capabilities 章节至关重要。它建立了提案阶段与规范阶段之间的契约。在填写此章节之前，请研究现有的规范。此处列出的每个功能都需要一个对应的规范文件。

      保持简明扼要（1-2 页）。关注“为什么”而不是“怎么做” —— 实现细节属于 design.md。

      这是基础 —— 规范、设计和任务都建立在此之上。
    requires: []

  - id: specs
    generates: "specs/**/*.md"
    description: 变更的详细规范
    template: spec.md
    instruction: |
      创建定义系统"应该做什么"的规范文件。

      为提案 Capabilities 章节中列出的每个功能创建一个规范文件：
      - 新增功能：使用提案中的精确 kebab-case 名称（specs/<capability>/spec.md）。
      - 修改功能：在创建增量规范时，使用项目目录中原有的规范文件夹名称（在 specs/<capability>/spec.md 中创建）。

      增量操作（使用 ## 标题）：
      - **ADDED Requirements**: 新功能
      - **MODIFIED Requirements**: 行为变更 - 必须包含完整的更新内容
      - **REMOVED Requirements**: 弃用的特性 - 必须包含 **Reason**（原因）和 **Migration**（迁移方案）
      - **RENAMED Requirements**: 仅限名称变更 - 使用 FROM:/TO: 格式

      格式要求：
      - 每个需求：`### 需求：<名称>` 后面跟描述
      - 使用 SHALL/MUST/必须/禁止等规范性词汇（避免使用 should/may）
      - 每个场景：`#### 场景：<名称>` 使用 当/那么（WHEN/THEN）格式
      - **关键提示**：场景标题必须恰好使用 4 个井号 (`####`)。使用 3 个井号或列表将导致处理失败。
      - 每个需求必须至少有一个场景。

      修改需求工作流：
      1. 在项目的 specs/<capability>/spec.md 中找到现有的需求
      2. 复制整个需求块（从 `### 需求：` 到所有场景）
      3. 粘贴到 `## 修改需求` 下并编辑以反映新行为
      4. 确保标题文本完全匹配（空格不敏感）

      常见陷阱：使用 MODIFIED 时只包含部分内容会导致归档时丢失细节。如果只是添加新关注点而不改变现有行为，请使用 ADDED 代替。

      示例：
      ```
      ## ADDED Requirements

      ### 需求：用户可以导出数据
      系统应当允许用户以 CSV 格式导出其数据。

      #### 场景：成功导出
      - **当** 用户点击“导出”按钮
      - **那么** 系统下载包含所有用户数据的 CSV 文件

      ## REMOVED Requirements

      ### 需求：旧版导出
      **Reason**: 被新导出系统取代
      **Migration**: 使用 /api/v2/export 处的新导出端点
      ```

      规范应当是可测试的 —— 每个场景都是一个潜在的测试用例。
    requires:
      - proposal

  - id: design
    generates: design.md
    description: 包含实现细节的技术设计文档
    template: design.md
    instruction: |
      创建说明“如何实现”变更的设计文档。

      何时包含 design.md（仅在符合以下任一条件时创建）：
      - 跨领域变更（涉及多个服务/模块）或新的架构模式
      - 新的外部依赖或重要的数据模型变更
      - 安全、性能或迁移的复杂性
      - 在编码前能从技术决策中获益的模糊性

      章节：
      - **Context**: 背景、当前状态、约束、利益相关者
      - **Goals / Non-Goals**: 此设计旨在实现的目标以及明确排除的目标
      - **Decisions**: 关键技术选择及其理由（为什么选 X 而不是 Y？）。列出每个决策考虑过的替代方案。
      - **Risks / Trade-offs**: 已知限制、可能出现的问题。格式：[风险] → 缓解措施
      - **Migration Plan**: 部署步骤、回滚策略（如果适用）
      - **Open Questions**: 待定决策或待解决的未知事项

      侧重于架构和方法，而不是逐行代码的实现。参考提案了解动机，参考规范了解需求。

      优秀的设计文档会解释技术决策背后的“原因”。
    requires:
      - proposal

  - id: tasks
    generates: tasks.md
    description: 可追踪任务的实施清单
    template: tasks.md
    instruction: |
      创建分解实现工作的任务列表。

      **重要提示：严格遵循以下模板格式。** 应用阶段会解析复选框格式来跟踪进度。不使用 `- [ ]` 格式的任务将不会被跟踪。

      指南：
      - 将相关任务分组到 ## 编号标题下
      - 每个任务必须是复选框：`- [ ] X.Y 任务描述`
      - 任务应该足够小，可以在一次会话中完成
      - 按依赖关系排序任务（什么必须先做？）

      示例：
      ```
      ## 1. 设置

      - [ ] 1.1 创建新模块结构
      - [ ] 1.2 向 package.json 添加依赖

      ## 2. 核心实现

      - [ ] 2.1 实现数据导出功能
      - [ ] 2.2 添加 CSV 格式化工具
      ```

      参考规范了解要构建的内容，参考设计了解如何构建它。每个任务应当是可验证的 —— 你能知道它何时完成。
    requires:
      - specs
      - design

apply:
  requires: [tasks]
  tracks: tasks.md
  instruction: |
    阅读上下文文件，逐个处理待办任务，并在完成后标记。如果遇到阻碍或需要澄清，请暂停。
